/**
 * This file is generated by scripts/index.mjs.
 */
import app from '../app';
import background from '../background';
import home from './home';
import settings_music from './settings_music';
import settings_theme from './settings_theme';
export default [app, background, home, settings_music, settings_theme];