import fs from 'node:fs/promises';

for (const lib of ['components', 'stages', 'entities', 'elements']) {
    const imports = [
        '/**',
        ' * This file is generated by scripts/index.mjs.',
        ' */',
    ];

    const index = [];

    for (const src of await fs.readdir(`src/${lib}`)) {
        if (src.endsWith('.ts')) {
            const name = src.slice(0, -3);
            imports.push(`import ${name} from '../${lib}/${name}';`);
            index.push(name);
        }
    }

    imports.push(`export default [${index.join(', ')}];`);
    await fs.writeFile(`src/build/${lib}.ts`, imports.join('\n'));
}
