import fs from 'node:fs/promises';

const imports = [
    '/**',
    ' * This file is generated by scripts/index.mjs.',
    ' */',
    `import { ui } from './ui';`,
    `import { createRoot } from './dom';`
];

for (const src of await fs.readdir('src/components')) {
    imports.push(`import '../components/${src.slice(0, -3)}';`);
}

imports.push(`createRoot(ui.app());`);

await fs.writeFile('src/client/client.ts', imports.join('\n'));
