import fs from 'node:fs/promises';

for (const lib of ['components', 'stages', 'entities']) {
    for (const section of ['home', 'game']) {
        const imports = [
            '/**',
            ' * This file is generated by scripts/index.mjs.',
            ' */',
        ];

        const index = [];

        for (const src of await fs.readdir(`src/${lib}`)) {
            if (src.endsWith('.ts')) {
                const name = src.slice(0, -3);
                imports.push(`import ${name} from '../${lib}/${name}';`);
                index.push(name);
            }
        }

        for (const src of await fs.readdir(`src/${lib}/${section}`)) {
            if (src.endsWith('.ts')) {
                const name = src.slice(0, -3);
                imports.push(`import ${name} from '../${lib}/${section}/${name}';`);
                index.push(name);
            }
        }

        imports.push(`export default [${index.join(', ')}];`);
        await fs.writeFile(`src/build/${lib}_${section}.ts`, imports.join('\n'));
    }
}

{
    const imports = [
        '/**',
        ' * This file is generated by scripts/index.mjs.',
        ' */',
    ];

    const index = [];

    for (const src of await fs.readdir(`src/elements`)) {
        if (src.endsWith('.ts')) {
            const name = src.slice(0, -3);
            imports.push(`import ${name} from '../elements/${name}';`);
            index.push(name);
        }
    }

    imports.push(`export default [${index.join(', ')}];`);
    await fs.writeFile(`src/build/elements.ts`, imports.join('\n'));
}