import fs from 'node:fs/promises';

const imports = [
    '/**',
    ' * This file is generated by scripts/index.mjs.',
    ' */',
];

for (const src of await fs.readdir('src/components')) {
    if (src !== 'index.ts') {
        imports.push(`import './${src.slice(0, -3)}';`);
    }
}

await fs.writeFile('src/components/index.ts', imports.join('\n'));
