import {promises as fs} from 'fs';

const imports = [
    '/**',
    ' * This file is generated by scripts/ui.mjs.',
    ' */',
    `import {ui} from './ui';`,
    `import {createRoot} from './dom';`
];

for (const src of await fs.readdir('src/components')) {
    imports.push(`import '../components/${src.slice(0, -3)}';`);
}

imports.push(`createRoot(ui.app);`);

await fs.writeFile('src/client/index.ts', imports.join('\n'));
