import {promises as fs} from 'fs';

const imports = [
    '/**',
    ' * This file is generated by scripts/ui.mjs.',
    ' */'
];

for (const src of await fs.readdir('src/components')) {
    imports.push(`import '../components/${src}';`);
}

await fs.writeFile('src/client/index.ts', imports.join('\n'));
