import { createState } from './state';
import { register } from './components';
import app from '../components/app';
import arena from '../components/arena';
import background from '../components/background';
import foreground from '../components/foreground';
import home from '../components/home';
import main from '../components/main';
import room from '../components/room';
import zoom from '../components/zoom';
register(app, null, createState);
register(arena, null, createState);
register(background, null, createState);
register(foreground, null, createState);
register(home, null, createState);
register(main, null, createState);
register(room, null, createState);
register(zoom, null, createState);